[package]
name = "test1"
version = "0.1.0"
edition = "2021"

[lib]
name = "test1"
path = "src/meth_with_more_digits.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

Veggies = {path = "src/Veggies"}
